version: 2.1

workflows:
  e2e:
    jobs:
      - build
      - local:
          requires:
            - build

      - global:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cypress/browsers:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v6-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v6-dependencies-

      - run:
          name: npm install
          command: |
            npm install --no-progress

          environment:
            npm_config_prefix: ~/.npm

      - save_cache:
          paths:
            - ~/.npm
          key: v6-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build
          environment:
            npm_config_prefix: ~/.npm
          command: |
            npm run build

      - persist_to_workspace:
          root: .
          paths:
            - .

  local:
    docker:
      - image: cypress/browsers:latest

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run E2E with locally installed cypress
          environment:
            npm_config_prefix: ~/.npm
            DEBUG: cy2
            NO_COLOR: 1
          # remove cypress as a peer dependecy
          # Set NODE_PATH to explicitly allow discovering the local ./e2e/cypress
          command: |
            npm uninstall cypress
            cd e2e
            npm install cypress --no-progress
            NODE_PATH=./node_modules node ./test-run.js
            NODE_PATH=./node_modules node ./test-spawn.js run

  global:
    docker:
      - image: cypress/browsers:latest

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run E2E with globally installed cypress
          environment:
            npm_config_prefix: ~/.npm
            DEBUG: cy2
            NO_COLOR: 1

          # Global installs on Unix systems go to {prefix}/lib/node_modules.
          # Global installs on Windows go to {prefix}/node_modules (that is, no lib folder.)
          command: |
            npm uninstall cypress
            cd e2e
            npm install --global cypress --no-progress
            NODE_PATH=$(npm prefix -g)/lib/node_modules node ./test-run.js
            NODE_PATH=$(npm prefix -g)/lib/node_modules node ./test-spawn.js run
