name: Bug report
description: Create a report to help us improve cy2
labels: bug

body:
  - type: checkboxes
    attributes:
      label: |
        Before opening, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/cy2/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/cy2/discussions).
          required: true
        - label: I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    attributes:
      label: Environment information
      description: |
        Please run the following command inside your project and copy/paste the output below:
        ```
        npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
        ```
      value: |
        <details>

        ```
        # Put output below this line


        ```

        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Command and Setup
      description: |
        - The exact command or code snipper used to run cy2
        - Your cloud provider and sorry-cypress setup details

    validations:
      required: true

  - type: textarea
    attributes:
      label: Full log and debug output
      description: |
        Run in debug mode to provide more info - error messages and stack traces.

        **👉🏻 Include the full log 👈🏻 - starting from running the command till receiving an error.**

        Attach a link / file for long outputs.

        Linux: `DEBUG=cy2*,cypress:* cy2 run ...`
        Windows: `cmd /V /C "set DEBUG=cy2*,cypress:*&& set CYPRESS_API_URL=some && cy2 run ..."`

        **Be sure to remove any sensitive data.**
      value: |
        <details>

        ```
        // Put your logs below this line


        ```

        </details>
    validations:
      required: true
