name: Feature Request
description: Request a new feature
labels: enhancement

body:
  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe the feature in details

    validations:
      required: true

  - type: textarea
    attributes:
      label: Example usage
      description: Please provide an example of how the feature will be used - code or command line
    validations:
      required: true
